### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Jake-Shadle** [LuoZijun/rust-core-video-sys#24]
https://github.com/LuoZijun/rust-core-video-sys/commit/2301c59ba18e570a0970cb82820f12e771b60398 bumped cfg-if to 1.0 but this was never released. This crate is the sole user of this old version out of the dozens of others that use it in our dependency graph.

**Comment by lu-zero** [comment]
Would be possible to let others maintain it (and publish it on crates.io)?

**Comment by Jake-Shadle** [comment]
We actually no longer use this crate but might be worth posting an issue and/or announcement somewhere to say you are looking for maintainers.

**Comment by lu-zero** [comment]
Did you find a replacement for core-video?

**Comment by Jake-Shadle** [comment]
We didn't have a direct dependency on it, it was a dependency of `winit` <= 0.26 and removed/replaced in 0.27.

**Comment by lu-zero** [comment]
I see, I hope the author @LuoZijun could tell us more.
